files:
  ignore:
    - 'node_modules/**/*.scss'
rules:
  class-name-format:
    - 1
    - convention: hyphenatedbem
  final-newline:
    - 0
  hex-notation:
    - 1
    - style: uppercase
  hex-length:
    - 1
    - style: long
  property-sort-order:
    - 1
    - order: smacss
  mixins-before-declarations:
    - 1
    - exclude: ['media-breakpoint-up']