language: php
sudo: false
php:
  - '7.3'

env:
  - NODE_RELEASE=10

before_install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`
  - cd -
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_RELEASE
  - nvm use $NODE_RELEASE

before_script:
  - composer install -n
  - composer update

script:
  - composer lint
